### ISSUE TITLE
Orphan pool and team rejoining

### ISSUE THREAD

**Issue by kishan-v** [ADimoska/SOMASExtended#24]
here's a brief outline of some logic we had to handle orphans a while back: 

Any team member that leaves a team or gets kicked out gets assigned to 
the 'orphan pool'. The orphan pool currently has the following type: 

⁠ map[uuid.UUID][]uuid.UUID ⁠

That is, a map of UUIDs (orphans) to slices of UUIDs. Each slice contains the teams that the orphan wishes to join, in order of preference. For example, if some orphan ⁠ c448hf ⁠ wants to join teams ⁠ ss9fj22 ⁠, ⁠ ffcc0d1 ⁠ and ⁠ 10vvnsa ⁠, and entry in the map will be: 

⁠ c448hf -> {ss9fj22, ffcc0d1, 10vvnsa}. ⁠

The server contains an ⁠ AllocateOrphans ⁠ function that does the following:

![image](https://github.com/user-attachments/assets/c43bcca4-06e3-4e74-be11-d84f2b66b341)

**Comment by kishan-v** [comment]
@nlewxxs :

There is some code on the ⁠ team1-server-agent-fix ⁠ branch (sorry that's just what we were working on at the time) in a file called ⁠ OrphanPool.go ⁠. It's not tested but let me know if it's worth using and I'll clean it up.

**Comment by nlewxxs** [comment]
@vedantvasugupta are you around sometime on thursday to look over this?

**Comment by arnavxkohli** [comment]
I believe this has been resolved?

**Comment by nlewxxs** [comment]
Waiting for someone to review and merge #65 so that I can combine the two different orphan pools together
(@vedantvasugupta and I implemented leaving and joining with separate pools, no biggie just needs to be put into one)

Won't hurt merging to main because everything that worked before will still work in isolation

Unless @arnavxkohli you think it's best to just continue off this branch and rebase off main?

**Comment by arnavxkohli** [comment]
Did you guys figure it out in the end? @vedantvasugupta @nlewxxs

**Comment by nlewxxs** [comment]
Not yet, I'm going to message @vedantvasugupta tomorrow bc a couple of his PRs have been up a while now, might have forgotten
